#!/bin/bash

#write a script that encrypts specified files using GPG or other encryption methods

file_encryption(){
        encryption=$(gpg -c SampleFile.txt)
        echo "$encryption"
}

file_encryption


output : 

gpg: AES256.CFB encrypted data
gpg: encrypted with 1 passphrase
#!/bin/bash
Date=03-05-2024
This is Shell scripting Task 2
